<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-custom">
            <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                    <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
                </a> <br>
                <?php echo (isset($this->menu) ? $this->menu : ''); ?>
            </div>
            <div class="panel-body">
               <form action="<?php echo BASE; ?>cadastro/cadastrar" class="form-horizontal" method="post">
                  
                    <div  class="form-group">
                        <label for="name" class="col-sm-3 control-label">Nome:</label>
                        <div class="col-sm-8">
                          <input required type="text" class="form-control" id="name" name="name" placeholder="Nome Completo" re>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">E-mail:</label>
                        <div class="col-sm-8">
                          <input required type="text" class="form-control" id="email" name="email" placeholder="seuemail@site.com.br">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="username" class="col-sm-3 control-label">Usuário:</label>
                        <div class="col-sm-8">
                          <input required type="text" class="form-control" id="username" name="username" placeholder="username">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label">Senha:</label>
                        <div class="col-sm-8">
                          <input required type="password" class="form-control" id="password" name="password" placeholder="Sua senha">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-9">
                          <button type="submit" class="btn btn-success">Cadastrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
