<div class="panel-body">
    <?php echo(isset($this->alert) ? $this->alert : ''); ?>
    <form action="<?php echo BASE; ?>login/logar" class="form-horizontal" method="post">

        <div class="form-group">
            <label for="username" class="col-sm-3 control-label">Usuário:</label>
            <div class="col-sm-8">
                <input required type="text" class="form-control" id="username" name="username" placeholder="username"
                       value="<?php echo $this->request->post('username') ?>">
            </div>
        </div>

        <div class="form-group">
            <label required for="password" class="col-sm-3 control-label">Senha:</label>
            <div class="col-sm-8">
                <input type="password" class="form-control" id="password" name="password" placeholder="Sua senha">
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-9">
                <button type="submit" class="btn btn-success">Entrar</button>
            </div>
        </div>
    </form>
</div>

